theme: jekyll-theme-minimal
title: Martin Bore
description: Senior IT-security engineer / head of UiO-CERT
logo: https://www.usit.uio.no/om/organisasjon/sst/stab/ansatte/bore/bore.jpg
show_downloads: false
