theme: jekyll-theme-minimal
title: Martin Bore
description: Head of UiO-CERT / Chief IT-security engineer
logo: https://www.usit.uio.no/om/organisasjon/sst/stab/ansatte/bore/bore.jpg
show_downloads: false
